import type { Config } from 'tailwindcss';

// Theme taken verbatim from the Stitch project "Mtokaahero Auto Services Marketplace"
// (design system "Kinetic High-Trust Automotive"), so Stitch markup ports class-for-class.
// Note the Stitch radius scale: rounded-lg is 4px and rounded-full is 12px.

const heading = ['var(--font-heading)', 'Space Grotesk', 'sans-serif'];
const body = ['var(--font-body)', 'Manrope', 'sans-serif'];
const mono = ['var(--font-mono)', 'JetBrains Mono', 'monospace'];

const config: Config = {
    content: ['./components/**/*.{js,ts,jsx,tsx}', './app/**/*.{js,ts,jsx,tsx}'],
    theme: {
        extend: {
            colors: {
                'on-surface': '#131b2e',
                'on-error': '#ffffff',
                'secondary-container': '#fea619',
                'surface-dim': '#d2d9f4',
                'surface-tint': '#2151da',
                'outline-variant': '#c4c5d7',
                'primary-container': '#1d4ed8',
                'on-primary-container': '#cad3ff',
                'tertiary-fixed-dim': '#ffb3b6',
                'surface-container-lowest': '#ffffff',
                'on-surface-variant': '#434655',
                'surface-container-low': '#f2f3ff',
                tertiary: '#8e0026',
                'surface-container-high': '#e2e7ff',
                'error-container': '#ffdad6',
                'inverse-primary': '#b7c4ff',
                'tertiary-fixed': '#ffdada',
                'on-primary-fixed-variant': '#0039b5',
                'inverse-surface': '#283044',
                'on-tertiary': '#ffffff',
                'secondary-fixed': '#ffddb8',
                'secondary-fixed-dim': '#ffb95f',
                'tertiary-container': '#ba0035',
                'on-secondary-fixed-variant': '#653e00',
                'primary-fixed-dim': '#b7c4ff',
                'on-primary': '#ffffff',
                primary: {
                    DEFAULT: '#0037b0',
                    hover: '#2563eb',
                    deep: '#1e40af',
                    subtle: '#eff6ff',
                    foreground: '#ffffff',
                },
                'on-primary-fixed': '#001551',
                surface: '#faf8ff',
                'surface-container': '#eaedff',
                'surface-container-highest': '#dae2fd',
                'on-secondary-container': '#684000',
                secondary: { DEFAULT: '#855300', foreground: '#ffffff' },
                'on-tertiary-fixed': '#40000c',
                'on-secondary': '#ffffff',
                'on-error-container': '#93000a',
                'on-secondary-fixed': '#2a1700',
                background: '#faf8ff',
                'inverse-on-surface': '#eef0ff',
                'surface-bright': '#faf8ff',
                'on-tertiary-fixed-variant': '#920028',
                'on-background': '#131b2e',
                'on-tertiary-container': '#ffc7c9',
                'surface-variant': '#dae2fd',
                'primary-fixed': '#dce1ff',
                error: '#ba1a1a',
                outline: '#747686',

                // Functional aliases used by the shared form primitives.
                foreground: '#131b2e',
                border: '#e2e8f0',
                input: '#cbd5e1',
                ring: '#2563eb',
                canvas: '#faf8ff',
                rescue: { DEFAULT: '#e11d48', subtle: '#fff1f2' },
                warning: { DEFAULT: '#f59e0b', subtle: '#fffbeb' },
                success: { DEFAULT: '#059669', subtle: '#ecfdf5' },
                destructive: { DEFAULT: '#ba1a1a', foreground: '#ffffff' },
                muted: { DEFAULT: '#f2f3ff', foreground: '#434655' },
                accent: { DEFAULT: '#eaedff', foreground: '#0037b0' },
                popover: { DEFAULT: '#ffffff', foreground: '#131b2e' },
                card: { DEFAULT: '#ffffff', foreground: '#131b2e' },
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
                pill: '9999px',
            },
            spacing: {
                'space-sm': '0.5rem',
                'margin-md': '2rem',
                gutter: '1rem',
                'space-xl': '2rem',
                'gutter-md': '1.5rem',
                'margin-lg': '3rem',
                'space-xs': '0.25rem',
                'space-md': '1rem',
                'gutter-lg': '2rem',
                margin: '1rem',
                'space-lg': '1.5rem',
            },
            fontFamily: {
                heading,
                body,
                mono,
                'headline-xl': heading,
                'headline-xl-mobile': heading,
                'headline-lg': heading,
                'headline-lg-mobile': heading,
                'headline-md': heading,
                'headline-sm': heading,
                'title-lg': body,
                'title-md': body,
                'body-lg': body,
                'body-md': body,
                'body-sm': body,
                'label-lg': body,
                'label-md': body,
                'code-sm': mono,
                'code-xs': mono,
            },
            fontSize: {
                'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '700' }],
                'headline-xl-mobile': ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
                'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '0', fontWeight: '600' }],
                'title-lg': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'title-md': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '600' }],
                'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
                'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
                'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
                'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
                'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
                'code-sm': ['12px', { lineHeight: '16px', letterSpacing: '-0.01em', fontWeight: '500' }],
                'code-xs': ['10px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '600' }],
            },
            boxShadow: {
                card: '0 1px 3px 0 rgba(15, 23, 42, 0.04), 0 1px 2px -1px rgba(15, 23, 42, 0.04)',
                raised: '0 4px 6px -1px rgba(15, 23, 42, 0.07), 0 2px 4px -2px rgba(15, 23, 42, 0.05)',
                modal: '0 25px 50px -12px rgba(15, 23, 42, 0.22)',
            },
            keyframes: {
                'accordion-down': {
                    from: { height: '0' },
                    to: { height: 'var(--radix-accordion-content-height)' },
                },
                'accordion-up': {
                    from: { height: 'var(--radix-accordion-content-height)' },
                    to: { height: '0' },
                },
            },
            animation: {
                'accordion-down': 'accordion-down 0.2s ease-out',
                'accordion-up': 'accordion-up 0.2s ease-out',
            },
        },
    },
    plugins: [require('tailwindcss-animate')],
};

export default config;
